services:
  - type: web
    runtime: docker
    name: quantitymeasurementapp-frontend
    plan: free
    healthCheckPath: /
    envVars:
      - key: API_UPSTREAM
        value: https://api-gateway-slc7.onrender.com
      - key: OAUTH_UPSTREAM
        value: https://authentication-service-wjg4.onrender.com
