services:
  - type: web
    runtime: docker
    name: quantitymeasurementapp-frontend
    plan: free
    healthCheckPath: /
    envVars:
      - key: API_UPSTREAM
        value: https://quantitymeasurementapp-1-ev12.onrender.com
      - key: OAUTH_UPSTREAM
        value: https://quantitymeasurementapp-1-ev12.onrender.com
